### ISSUE TITLE
How to find “Video with Q&A”/ “Chat” matrix links

### ISSUE THREAD

**Issue by jellelicht** [mttcrsp/fosdem#101]
Thanks a bunch for working on this app! Is there any way I can reach the matrix links for each talk as well?

**Comment by mttcrsp** [comment]
Hi, thanks for the feedback!

About videos

I just pushed an update that allows you to watch livestreams over the two days of the conference. Recordings should also should appear in the app as soon they become available.

About Matrix links

Unfortunately the app doesn't display Matrix links anywhere. The schedule API the app uses ([Pentabarf XML](https://fosdem.org/2021/schedule/xml)) does not provide them. Looking through the website codebase though, I see [they are generated on the fly](https://github.com/FOSDEM/website/blob/1b81ac27c20fd429e839f8e70e0b40568dc63165/lib/helpers/schedule_helpers.rb#L401) based on a combination of event type, room, and track. It shouldn't be too difficult to add support for them.
