### ISSUE TITLE
FOSDEM 2023 support

### ISSUE THREAD

**Issue by Doctor-love** [mttcrsp/fosdem#102]
Greetings Matteo,

Thanks for a nice looking app! Would love to see it updated for FOSDEM 2023 - doesn't look like a huge change unless they've changed their feeds.

**Comment by mttcrsp** [comment]
Hi @Doctor-love, I'm glad to hear that you like the app. I've just updated it with support for 2023 and will be submitting the new version to the store in the coming days. You can get a preview by joining the public TestFlight at this link: https://testflight.apple.com/join/UKoTtP28.

**Comment by Doctor-love** [comment]
Joined the test-flight and it seems to work like a charm! Hope to see you there!
