### ISSUE TITLE
Macos build + favourite syncing through iCloud

### ISSUE THREAD

**Issue by xvilo** [mttcrsp/fosdem#103]
It would be great if we could consider building a macOS compatible app. For integration, it would be cool if favourites are synced through iCloud, so one can have the same view on both iOS and macOS

**Comment by mttcrsp** [comment]
Hey @xvilo, thank you very much for the feedback!

In the past weeks, I have been working on implementing iCloud sync and I would like to release it as part of version 1.4.1. You can get a preview by joining the public TestFlight at this link: https://testflight.apple.com/join/UKoTtP28.

Regarding macOS support, the iPad version of the app can already be downloaded and run on Apple Silicon Macs. I was wondering whether you knew this as the readme did not mention it. I have updated readme to better reflect this.

I have considered introducing a dedicated Mac Catalyst build to extend support for Intel Macs. I am currently slightly hesitant as it would introduce an additional moving piece that less and less people will take advantage of in the coming years. This could change if there is interest in it.
