### ISSUE TITLE
Missing video links

### ISSUE THREAD

**Issue by dvaerum** [mttcrsp/fosdem#107]
For some reason, some of the talks don’t show an option to play an video

![60655C31-C90D-42A0-9EB6-90A2473DCCE6](https://user-images.githubusercontent.com/6872940/221342306-9e649a19-7f6e-4d7c-8fcb-72d6aefc3f0c.png)

event through the video is on the website for the talk

![A450C169-80B2-4D8B-A8D0-355555310A64](https://user-images.githubusercontent.com/6872940/221342355-e3d8b162-ff79-4a1d-8366-0ef819445cf0.png)

**Comment by mttcrsp** [comment]
Hey @dvaerum, thank you for taking the time to file this! I updated the app with a fix for this issue and will be submitting a new 1.4.1 version to the store in the coming days. You can get a preview by joining the public TestFlight at this link: https://testflight.apple.com/join/UKoTtP28.

**Comment by dvaerum** [comment]
I am the one there thanks 🙏
I have test your fix and it works 🎉
Thanks for the quick resolution 😁
