### ISSUE TITLE
Support for 2024

### ISSUE THREAD

**Issue by andreicek** [mttcrsp/fosdem#108]
The schedule for 2024 is live and I would like to help add support for the year. I've looked at the ways it was done in the past, but the script has moved. 

Can I please ask for some pointers?

**Comment by andreicek** [comment]
Hints on how to even run the project would be very appreciated as well :)

**Comment by mttcrsp** [comment]
> The schedule for 2024 is live and I would like to help add support for the year. I've looked at the ways it was done in the past, but the script has moved.
> 
> Can I please ask for some pointers?

Hey @andreicek, thank you very much for showing up to help! You are right, I replaced the script with a debug menu entry that generates the new year database file asset and logs its path to the console. (see video below) This path will point to a `db.sqlite` file that you use to replace the old one in `App/Resources`.

The only other required steps to get the app running for the new year are:
- updating the [`YearsService.current` constant](https://github.com/mttcrsp/fosdem/blob/d79ddfb5a4451bf31bb4b946ecb9e2e41adc8a45/App/Sources/Services/YearsService.swift#L9),
- bumping the [version number in `project.yml`](https://github.com/mttcrsp/fosdem/blob/ae6f14cdcbfde2fa2fd24d06d26b87a55801fa18/project.yml#L43).

Some additional optional things I usually do when alongside the update:
- download the latest XML version of the schedule¹ and update the [schedule parsing smoke tests](https://github.com/mttcrsp/fosdem/blob/d79ddfb5a4451bf31bb4b946ecb9e2e41adc8a45/App/Tests/ScheduleXMLParserTests.swift#L7) in `ScheduleXMLParserTests ` to verify it;
- update the [`TimeService` date constant](https://github.com/mttcrsp/fosdem/blob/d79ddfb5a4451bf31bb4b946ecb9e2e41adc8a45/App/Sources/Services/TimeService.swift#L23) to match the first day of the conference to simplify troubleshooting of the _Events in the next 30 minutes_ functionality.

I took care of this in d79ddfb.

¹ Use `curl https://fosdem.org/2024/schedule/xml -o App/Tests/Resources/Schedules/2024.xml` for this

https://github.com/mttcrsp/fosdem/assets/7688838/60b75184-4715-4703-bbd4-d4fc736bf8d0

**Comment by mttcrsp** [comment]
> Hints on how to even run the project would be very appreciated as well :)

Cloning and running the `brew bundle && make generate_project` command listed in the README should get you an `.xcodeproj` file you can use to build and run the app. Please, let me know any of this is not working for you.

**Comment by andreicek** [comment]
Ah you did it all! This issue can then be closed, I guess.

The commit you did e4840372e92154a646804b00cbf0210e5da392ae was what I was missing, I was not able to start the project due to the error:

```
Missing path (/Users/andreicek/src/0x7fdev/fosdem/Vendor/GRDB.xcframework/ios-arm64_x86_64-simulator/dSYMs) from XCFramework 'GRDB.xcframework' as defined by 'DebugSymbolsPath' in its `Info.plist` file
```

which is now gone.

Sorry I wasn't of more help.
